### ISSUE TITLE
monit defaults always installed

### ISSUE THREAD

**Issue by scottnonnenberg** [ANXS/nginx#16]
I tried to opt out of monit, but it didn't work. Without the `Ansibles.monit` galaxy role installed, I get this:

```
ERROR: cannot find role in /Users/scottnonnenberg/Development/config/roles/Ansibles.monit or /Users/scottnonnenberg/Development/config/Ansibles.monit or /etc/ansible/roles/Ansibles.monit
```

With it installed I get default monit configuration: 

``` shell
TASK: [Ansibles.monit | Monit | Make sure monit is installed] ***************** 
<linode2> REMOTE_MODULE apt pkg=monit state=present
ok: [linode2] => {"changed": false}

TASK: [Ansibles.monit | Monit | Update the monit configuration (/etc/monit/monitrc)] *** 
ok: [linode2] => {"changed": false, "gid": 0, "group": "root", "mode": "0600", "owner": "root", "path": "/etc/monit/monitrc", "size": 6400, "state": "file", "uid": 0}

TASK: [Ansibles.monit | Monit | Copy the sshd/ntp/chron monit service files] *** 
ok: [linode2] => (item=sshd) => {"changed": false, "gid": 0, "group": "root", "item": "sshd", "mode": "0644", "owner": "root", "path": "/etc/monit/conf.d/sshd", "size": 249, "state": "file", "uid": 0}
ok: [linode2] => (item=cron) => {"changed": false, "gid": 0, "group": "root", "item": "cron", "mode": "0644", "owner": "root", "path": "/etc/monit/conf.d/cron", "size": 196, "state": "file", "uid": 0}
ok: [linode2] => (item=ntp) => {"changed": false, "gid": 0, "group": "root", "item": "ntp", "mode": "0644", "owner": "root", "path": "/etc/monit/conf.d/ntp", "size": 248, "state": "file", "uid": 0}
```

But no nginx-specific monit configuration, as expected:

```
TASK: [Ansibles.nginx | Nginx | | (Monit) Copy the nginx monit service file] *** 
skipping: [linode2]
```

This was my playbook:

``` yaml

---
- hosts: load
  sudo: yes
  vars:
    nginx_install_method: "source"
    nginx_source_version: "1.7.2"
    nginx_source_modules_included:
      http_ssl_module: "--with-http_ssl_module"
    monit_protection: no
  roles:
    - { role: Ansibles.nginx, monit_protection: no }
```
