### ISSUE TITLE
change how modules are enable

### ISSUE THREAD

**Issue by otakup0pe** [ANXS/nginx#39]
Currently we enable extra modules by specifying the full string that is passed to `configure`. It would be much cleaner to specify them by a simple bool.

Compare the two following YAML snippets.

````
nginx_source_modules_included:
  http_stub_status_module: "--with-http_stub_status_module"

nginx_source_modules_included:
  http_stub_status_module: yes
````
