### ISSUE TITLE
Notify reload nginx after updating configs for site inventories

### ISSUE THREAD

**Issue by boosh** [ANXS/nginx#55]
`nginx/tasks/site.yml` templates site inventories with:
```
- name: Nginx | Update the configurations for the sites inventory
  template:
    src: site.j2
    dest: "{{nginx_dir}}/sites-available/{{item.server.name}}"
  with_items: nginx_sites
  when: nginx_sites|lower != 'none'
```
This should be changed to include:
```
  notify:
    - reload nginx
```
That way, any changes to a site's config will make nginx reload, whereas at the moment those config changes are written to config files but nginx isn't reloaded if the site is already enabled.
