### ISSUE TITLE
relative paths are broken when using ansible2.0.0beta3

### ISSUE THREAD

**Issue by iamjochem** [ANXS/nginx#65]
the `src` attributes in various tasks/module/*.yml files are incorrect (or incompable with upcoming asible version) .e.g.

you have this (does not work):
```yml
# file: nginx/tasks/modules/authorized_ips.yml

- name: Nginx | Modules | Updated the authorized_ip file
  template:
    src: ../../templates/modules/authorized_ips.j2
    dest: "{{nginx_dir}}/authorized_ips"
    owner: root
    group: root
    mode: 0644
```

I had to change it to this (works):

```yml
# file: nginx/tasks/modules/authorized_ips.yml

- name: Nginx | Modules | Updated the authorized_ip file
  template:
    src: modules/authorized_ips.j2
    dest: "{{nginx_dir}}/authorized_ips"
    owner: root
    group: root
    mode: 0644
```

it seems that ansible changed the way relative paths in 'template' module parameters are resolved (I have no experience with current/previous ansible version - so this is an educated guess).

PS - I'm an ansible noob - go easy :-)
